name: todo_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.17.1 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    animations: ^2.0.0
    cupertino_icons: ^1.0.2
    fluro: ^2.0.3
    flutter_svg: ^1.1.1+1
    fluttertoast: ^8.0.7
    json_annotation: ^4.6.0
    kiwi: ^4.0.2
    path_provider: ^2.0.1
    provider: ^6.0.3
    shared_preferences: ^2.0.5
    sqflite: ^2.0.0+3
    table_calendar: ^3.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner: ^2.1.11
    json_serializable: ^6.3.1
    kiwi_generator: ^4.0.2
    flutter_launcher_icons: "^0.13.0"

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
    uses-material-design: true

    assets:
        - assets/
