name: todo_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.6
  provider: ^5.0.0
  table_calendar: ^3.0.0

  fluro: ^2.0.3
  flutter_svg: ^0.22.0

  sqflite: ^2.0.0+3
  path_provider: ^2.0.1

  shared_preferences: ^2.0.5

  kiwi: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  kiwi_generator: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/
